### ISSUE TITLE
Issue with collection detection

### ISSUE THREAD

**Issue by green-arrow** [fotinakis/jsonapi-serializers#14]
We're currently using [Sequel](http://sequel.jeremyevans.net) for our data layer, and it happens that a `Sequel::Model` has an `each` method on individual models. This causes a `JSONAPI::Serializer::AmbiguousCollectionError`, because the test checks for that method.

Would it be beneficial to switch that check to use something like this (line 255 of `serializer.rb`):

```ruby
if objects.kind_of?(Array)
```

**Comment by fotinakis** [comment]
I'm checking for "each" as a duck-typing check so that it works for generically for types like `ActiveRecord::Relation`, which a strict type check like `is_a?(Array)` would not cover.

Why in the world does Sequel do that? :) We'd either have to find either a better duck-typing check that would fit with Sequel or maybe allow you to pass `skip_collection_check` or something stupid.

**Comment by green-arrow** [comment]
Ah, I was not aware of the `ActiveRecord` issue. Your guess is as good as mine on the Sequel issue :)

I would be ok with a `skip_collection_check`, or maybe a `force_single_object` or something like that.

I'd be happy to submit another PR for that if we can decided on what to call it.

**Comment by fotinakis** [comment]
Trying to come up with something...maybe `verify_collections: false` in the options hash and set it to true by default?

**Comment by fotinakis** [comment]
Completed in #16
