### ISSUE TITLE
Serializing a new record returns empty hash

### ISSUE THREAD

**Issue by beechnut** [fotinakis/jsonapi-serializers#19]
I'm [testing my serializers](https://github.com/beechnut/know-place-api/blob/data_connections/test/serializers/aggregator_serializer_test.rb#L29), and found that the attributes for new records -- that is, records that are not persisted -- are serialized to an empty hash.

```ruby
> p = Place.new(id: 12, name: "Boston", description: "Hey Beantown!")
 => #<Place id: 12, name: "Boston", description: "Hey Beantown!", geometry: nil, created_at: nil, updated_at: nil>
> p.attribute_names.map {|a| p.send(a) }
 => [12, "Boston", "Hey Beantown!", nil, nil, nil]
> JSONAPI::Serializer.serialize( p )
 => {"data"=>{"id"=>"12", "type"=>"places", "attributes"=>{}, "links"=>{"self"=>"/places/12"}}}
```

I don't consider this a bug, but it is getting in the way of my tests, and I think it's solvable. I'm happy to do a PR, but I could use a little advice on how to get started. I think this behavior is happening [around here](https://github.com/fotinakis/jsonapi-serializers/blob/b21119720fa4586f3af164905da937d37d8d9b76/lib/jsonapi-serializers/attributes.rb#L28) but I'd appreciate confirmation of that before diving in.

**Comment by fotinakis** [comment]
Interesting! jsonapi-serializers doesn't actually know anything about ActiveRecord objects, it simply pulls attributes defined by the serializer, so I would definitely consider that a bug if it was true. However, it looks like you're probably just defining the serializers incorrectly (ie. https://github.com/beechnut/know-place-api/blob/data_connections/app/serializers/place_serializer.rb doesn't have any `attribute` lines declared at all). Check out the readme for examples: https://github.com/fotinakis/jsonapi-serializers

Closing because this is not actually a bug, but feel free to re-open if you find that it is.

**Comment by beechnut** [comment]
Oh, hubris mine!

> "I did it correctly the first time, so the second time, when there are errors, there must be bugs!"
> ~ @beechnut, 2015

Thanks for responding so quickly, and for proofreading my serializer.
