### ISSUE TITLE
[question] Any tips on deserializing/parsing JSONAPI incoming payloads?

### ISSUE THREAD

**Issue by aars** [fotinakis/jsonapi-serializers#55]
@fotinakis (and others of course): What do you use to parse and process incoming JSONAPI messages? Any tips/hints?

I tried this new gem today: https://github.com/beauby/jsonapi_parser which is simple but works well for simple parsing. 

Of course the next step is to actually process the data, in my case through Sequel in a Sinatra app.
 I'm wondering in how far this could (or maybe more importantly, *should*) be generic. Handling relationships, or even inserting new models/objects as new relationships all through one posted JSONAPI document/payload for example.

I'd love to hear your thoughts.

PS: I hope it's alright to contact you through github issues. I don't see you on gitter and I don't have (or want) a Twitter account ;)

Cheers

**Comment by fotinakis** [comment]
My answer is that, because I'm using Rails, I usually just use [strong_parameters](https://github.com/rails/strong_parameters) and a private method in my controller to parse them.

```ruby
class Api::V1::FooController < Api::V1::BaseController
  def create
    foo = FooService.create_foo(
      some_attribute: valid_params['attributes']['some-attribute'],
      another_attribute: valid_params['attributes']['another-attribute'],
    )
    render json: JSONAPI::Serializer.serialize(foo)
  end

  private def valid_params
    params.require('data').require('attributes').permit(
      'some-attribute',
      'another-attribute',
    )
    params['data']
  end
end
```

I usually find this is simple and clear and Good Enough, and makes it clear when looking at the controller how API calls are parsed. The `require` lines (though they confusingly return the object they require) will raise an error if the request does not contain `data` or `attributes` etc, so users get a little bit of early validation if they don't send the right JSON:API format, and then the service object (and the underlying model when it creates it) will perform the rest of the validations.

Those are my thoughts, though my APIs are still pretty simple I haven't hit a lot of cases where I need a more complicated parsing system yet.

**Comment by aars** [comment]
Thanks. It's probably a good idea to keep things clear and explicit yes. Do you have any magic that handles many-to-many relationships where you have to address a join-table (that is most-likely not API resource?), or is that handled explicitly in each route/methods as well?

Somewhat unrelated: are you combining query params and body params (jsonapi document) in this case?

**Comment by fotinakis** [comment]
I try to never mix query parameters with POST requests, so everything is there in the POST body. But yes, Rails does not distinguish between the two and merges them into `params` (which I don't love). I believe the JSON:API spec only uses query params with GET requests, thankfully.

For the many-to-many question, can you clarify a bit more? Do you mean creating a relationship via a POST request that happens to touch a many-to-many relationship? I guess my answer is the same either way, I don't care about those things at this layer, I always parse the attributes and hand them off to a service object, and it's the service object's job to understand the underlying data models, JOINs, business logic, etc. This API handler becomes a perfect decoupling point for what I present to my users (JSON API) and how it's actually stored/managed internally. I have a couple of many-to-many bridge tables like I think you're talking about, but like you said they are not API resources and I don't ever expose them in the API layer. They are only used internally, from the perspective of one object in the API, they just look like a flat one-to-many relationship and I just access them by grabbing `valid_params['relationships']['data'].map { |linkage| linkage['id'] }` or something and passing it off to the service object.

Hope that helps!

**Comment by aars** [comment]
That does help! I need to build me some domain specific service objects between my sinatra app and Sequel models. That immediately impacts my desire to automate and simplify these things there :smile: 

Thanks a lot!

**Comment by fotinakis** [comment]
Excellent! :) Glad I could help.

IMO this architecture also helps dramatically simplify testing concerns, because then your API tests can just verify things are wired up correctly but not have to test business logic (same with your models, they are just unit tested). Your service object tests become the true tests of your business logic and are the re-usable parts of your system, you can call service objects methods everywhere internally without caring about HTTP requests—also then you don't have to do nasty things like duplicate the logic that is held in API controllers because it's inaccessible, or craft super contrived API requests just to exercise the business logic trapped in your controllers. Service objects :+1:.

**Comment by lowski** [comment]
@fotinakis probably I'm late to the party but maybe it would be good to mention in the README how to convertion from dasherized keys to underscored (in params)? It will make it easier to pass to the Rails models.

I mean something like this:

```
ActionDispatch::Http::Parameters::DEFAULT_PARSERS[:api_json] = lambda do |body|
  json = JSON.parse(body)
  json = json.deep_transform_keys!(&:underscore)
  json.with_indifferent_access
end
```

WDYT?
