### ISSUE TITLE
Pagination alternatives

### ISSUE THREAD

**Issue by beechnut** [fotinakis/jsonapi-serializers#9]
The [README](https://github.com/fotinakis/jsonapi-serializers/#unfinished-business) suggests that pagination won't be supported in the gem itself, but I'm looking for a way to add it in manually.

I successfully edited the links on the object record:

```ruby
# app/serializers/project_serializer.rb
def links
    {
      :self => "/#{type}/#{id}",
      :next => object.next ? "/#{type}/#{object.next.id}" : nil,
      :prev => object.prev ? "/#{type}/#{object.prev.id}" : nil
    }
end
```

which resulted in:

```json
# ... inside a single resource object
links": {
    "self": "/projects/BBAD49FC-9EF5-E411-BC1F-96147297305B",
    "next": "/projects/9B46559C-9DF5-E411-BC1F-96147297305B",
    "prev": null
},
# ...
```

I have custom pagination links ready to go, but haven't been able to figure out how to add them.

Is there a way to add a top-level `links` object [(specified here)](http://jsonapi.org/format/#fetching-pagination) to the root of the response, so that it would look like this?

```
{
  data: [...],
  included: [],
  links: {}
}
```

Thanks for a great gem, by the way.

**Comment by beechnut** [comment]
For anyone who stumbles upon this in the near future, this is my temporary solution.

Since `JSONAPI::Serializer#serialize` just returns a hash, you can serialize the object, then manipulate hash at your discretion. It's not a clean separation of concerns, which is why this is just a temporary hack, but it gets the job done for now.

```ruby
# app/controllers/projects_controller.rb
def index
  @projects = Project.all.page(page_number).per(per_page)
  json = JSONAPI::Serializer.serialize(@projects, include: includes, is_collection: true)
  json[:links] = paginate(@projects)
  render json: json
end
```
Where `#paginate` is an included helper method that returns a hash like:

```ruby
{ 
  self: "/projects?page[number]=1",
  next: "/projects?page[number]=2",
  prev: null,
  # ...
}

**Comment by fotinakis** [comment]
Nice workaround—so, the first and easiest part of this is probably that we should just let you pass a `links` arg into `serialize` to get them included in the root. That would at least get rid of some of the coupling above and then it is really pretty easy to just do the page(..).per(..) calls that you have to find the right objects, which you would have to do anyway since this gem doesn't perform any querying for you.

I haven't thoroughly read the pagination part of the spec yet, but I have a feeling this will get you most of the way? Happy to accept a PR for this, it'd be pretty simple to add, or I'll hopefully have time to take a look next week.
